#!/bin/bash

# =========================================
# IRIS Bootstrap Script
# Date Created: 2019.12.11
# Date Edited: 2019.12.15
# Copyright (c) 2019 Digital Warrior Labs
# Author: Nathan Martindale
# =========================================

# color constants
C_CYAN_L="\033[1;36m"
C_RED="\033[0;31m"
C_GREEN="\033[0;32m"
C_RESET="\033[0m"

# welcome message
echo -e "\n${C_CYAN_L}IRIS${C_RESET} Bootstrap Script"
echo -e "Digital Warrior Labs"

# NOTE: might be useful to have a log function that prints both to console and log file

# check if a particular program/file exists on the system or not
function check_tool {
	echo -en "Checking $1... "
	if hash $1 2>/dev/null; then 
		echo -e "${C_GREEN}GOOD${C_RESET}"
		return 0
	else
		echo -e "${C_RED}MISSING${C_RESET}"
		return 1
	fi
}

# check if most core tools available
echo -e "\nChecking for minimally required software..."
if ! check_tool git; then
	if check_tool pacman; then
		sudo pacman -S git
	elif check_tool apt-get; then
		sudo apt-get install git
	else
		echo -e "${C_RED}ERROR - No known package manager with which to install git${C_RESET}"
		# TODO: handling
		exit
	fi
fi

# pull the core repo and start it's initial setup process
echo "Pulling core IRIS repository..."
git clone https://github.com/WildfireXIII/iris-core.git $pkg_dir/iris-core

echo "Minimal bootstrap complete."
echo "Ceding control to core setup protocols..."
bash $pkg_dir/iris-core/setups/initial_setup.sh
